config/routes.rb
Rails.application.routes.draw do
  resources :corporacions do
  	resources :users
  end
  #resources :users
  get 'login' => 'login#index', as: 'login'
  post 'login'=> 'login#login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corporacion.rb
class Corporacion < ApplicationRecord

	has_many :users

end

app/models/user.rb
class User < ApplicationRecord

	belongs_to :corporacion

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/corporacions_controller.rb
class CorporacionsController < ApplicationController
  before_action :set_corporacion, only: [:show, :edit, :update, :destroy]

  # GET /corporacions
  # GET /corporacions.json
  def index
    @corporacions = Corporacion.all
  end

  # GET /corporacions/1
  # GET /corporacions/1.json
  def show
  end

  # GET /corporacions/new
  def new
    @corporacion = Corporacion.new
  end

  # GET /corporacions/1/edit
  def edit
  end

  # POST /corporacions
  # POST /corporacions.json
  def create
    @corporacion = Corporacion.new(corporacion_params)

    respond_to do |format|
      if @corporacion.save
        format.html { redirect_to corporacions_url, notice: 'Corporacion was successfully created.' }
        format.json { render :show, status: :created, location: @corporacion }
      else
        format.html { render :new }
        format.json { render json: @corporacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /corporacions/1
  # PATCH/PUT /corporacions/1.json
  def update
    respond_to do |format|
      if @corporacion.update(corporacion_params)
        format.html { redirect_to corporacions_url, notice: 'Corporacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @corporacion }
      else
        format.html { render :edit }
        format.json { render json: @corporacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corporacions/1
  # DELETE /corporacions/1.json
  def destroy
    @corporacion.destroy
    respond_to do |format|
      format.html { redirect_to corporacions_url, notice: 'Corporacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_corporacion
      @corporacion = Corporacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def corporacion_params
      params.require(:corporacion).permit(:nombre, :rut, :contraseña, :sucursal, :filas)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  	@user = User.new
  end

  def login
  	logger.info user_params
  	correo = user_params[:correo]
  	password = user_params[:contraseña]

  	if correo == 'admin@admin.cl' and password == '123456'
  		redirect_to corporacions_path, notice: 'Inicio de sesión exitosa.'
  	else
  		@user = User.new
  		@user.errors.add(:base, :is_invalid,
  message: "Credenciales invalidos")
  		render :index
  	end

  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:correo, :contraseña)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_corporacion_id

  # GET /users
  # GET /users.json
  def index
    @users = User.where(corporacion_id: @corporacion_id)
    #logger.info params[:corporacion_id]
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    #logger.info params[:corporacion_id]
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)

    corporacion_id = user_params[:corporacion_id]

    @user[:isAdmin] = 0
    #@user.corporacion_id = corporacion_id

    logger.info @user.as_json


    respond_to do |format|
      if @user.save
        format.html { redirect_to corporacion_users_path(corporacion_id), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    corporacion_id = corporacion_params[:corporacion_id]
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to corporacion_users_path(corporacion_id), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to corporacion_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_corporacion_id
      @corporacion_id = params[:corporacion_id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nombre, :apellido, :rut, :correo, :contraseña, :sucursal, :filas,:corporacion_id)
    end

    def corporacion_params
      params.require(:user).permit(:corporacion_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

 def form_errors(errors)
      if errors.empty?
        return
      end
      e = '<div id="error_explanation" class="alert alert-danger col-md-11" role="alert">
		<a href="#" data-dismiss="alert" class="close">×</a>
        <h4>Se encontraron los siguientes errores:</h4>
        <ul id="list_errors">'
			for m in errors.full_messages.each
				e = e + "<li>" + m.to_s + "</li>\n"
			end
			e = e + "</ul></div>"
      return e.html_safe
 	end

  def form_notice(errors)
      logger.info(errors)
      if !errors
        return
      end
      e = '<div id="error_explanation" class="alert alert-danger col-md-11" role="alert">
    <a href="#" data-dismiss="alert" class="close">×</a>
        <h4>Se encontraron los siguientes errores:</h4>
        <ul id="list_errors">'
      
      e = e + "<li>" + notice + "</li>\n"
      e = e + "</ul></div>"
      return e.html_safe
  end

  def is_whole_number(variable)
    return variable % 1 == 0
  end
 
end

app/helpers/corporacions_helper.rb
module CorporacionsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/corporacions/_form.html.erb
<%= form_with(model: corporacion, local: true) do |form| %>
  <% if corporacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(corporacion.errors.count, "error") %> prohibited this corporacion from being saved:</h2>

      <ul>
      <% corporacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :rut %>
    <%= form.text_field :rut %>
  </div>

  <div class="field">
    <%= form.label :contraseña %>
    <%= form.text_field :contraseña %>
  </div>

  <div class="field">
    <%= form.label :sucursal %>
    <%= form.text_field :sucursal %>
  </div>

  <div class="field">
    <%= form.label :filas %>
    <%= form.text_field :filas %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/corporacions/edit.html.erb
<h1>Editing Corporacion</h1>

<%= render 'form', corporacion: @corporacion %>

<%= link_to 'Show', @corporacion %> |
<%= link_to 'Back', corporacions_path %>

app/views/corporacions/index.html.erb
<%= stylesheet_link_tag "views/index.css" %>

<nav class="navbar navbar-expand-lg navbar-dark" style="background:#0E9CC8;">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="ml-auto">
      <div class="shape_perfil"></div>
      <div class="perfil">Tu perfil</div>
    </div>
  </div>
</nav>

<div class="rectangle">

  <div class="logo"></div>
  
  <div class="group">
    <div class="background">
      <div class="corporaciones"> Corporaciones</div>
    </div>
  </div>
  
  <div class="shape_usuarios"></div>
  <div class="usuarios">Usuarios</div>

  <div class="shape_home"></div>
  <div class="home">Sucursales</div> 

  <div class="shape_modulos"></div>
  <div class="modulos">Modulos</div>  


  <%= link_to 'Cerrar Sesión', login_path, :class =>'cerrar_sesion'%>

  <div class="listado">Listado de Corporaciones/Divisiones</div>

  <%= button_to 'Agregar Corporación', new_corporacion_path,method: :get, :class => 'agregar' %>

  <table class="table" style="position: absolute;
    width: 1040px;


      left: 290px;
      top: 282px;

      border: 1px solid #DDDDDD;">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Rut</th>
      <th>Contraseña</th>
      <th>Sucursal</th>
      <th>Filas</th>
      <th colspan="3" style="text-align: center;">Config</th>
    </tr>
  </thead>
  <tbody>
    <% @corporacions.each do |corporacion| %>
      <tr>
        <td><%= corporacion.nombre %></td>
        <td><%= corporacion.rut %></td>
        <td><%= corporacion.contraseña %></td>
        <td><%= corporacion.sucursal %></td>
        <td><%= corporacion.filas %></td>
        <td><%= link_to (fa_icon "users"), corporacion_users_path(corporacion.id) %></td>
        <td><%= link_to (fa_icon "edit"), edit_corporacion_path(corporacion) %></td>
        <td><%= link_to (fa_icon "trash"), corporacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>    
  
</div>

app/views/corporacions/new.html.erb
<h1>New Corporacion</h1>

<%= render 'form', corporacion: @corporacion %>

<%= link_to 'Back', corporacions_path %>

app/views/corporacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @corporacion.nombre %>
</p>

<p>
  <strong>Rut:</strong>
  <%= @corporacion.rut %>
</p>

<p>
  <strong>Contraseña:</strong>
  <%= @corporacion.contraseña %>
</p>

<p>
  <strong>Sucursal:</strong>
  <%= @corporacion.sucursal %>
</p>

<p>
  <strong>Filas:</strong>
  <%= @corporacion.filas %>
</p>

<%= link_to 'Edit', edit_corporacion_path(@corporacion) %> |
<%= link_to 'Back', corporacions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppAdmin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag  'application'%>
    <%= javascript_include_tag 'application'%>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<%= stylesheet_link_tag "views/login.css" %>

<div class="rectangule4">

	<%= form_for(@user, url: login_path, html: {role: "form",multipart: true, method: :post}) do |form| %>
		
		<div class="logo"></div>

		<div class="rectangule3">
			<%= form_errors(@user.errors)%>
		</div>

		<div class="ingrese">
			Ingrese tus datos para iniciar sesión
		</div>
		
		<%= form.text_field :correo, placeholder: "Escribe Correo", :class =>'rectangle_two' %>

		<%= form.text_field :contraseña, placeholder: "Escribe Password", :class =>'rectangle' %>
	

		<div class="group">
			<%= form.submit 'Iniciar Sesion', :class => 'rectangule2'%>
			
		</div>

	<% end %>
</div>

app/views/users/_form.html.erb
<%= form_errors(@user.errors)%>
<%= form_for([:corporacion, @user], html: {role: "form",multipart: true, method: :post}) do |form| %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido %>
  </div>

  <div class="field">
    <%= form.label :rut %>
    <%= form.text_field :rut %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_field :correo %>
  </div>

  <div class="field">
    <%= form.label :contraseña %>
    <%= form.text_field :contraseña %>
  </div>

  <div class="field">
    <%= form.label :sucursal %>
    <%= form.text_field :sucursal %>
  </div>

  <div class="field">
    <%= form.label :filas %>
    <%= form.text_field :filas %>
  </div>

  <%= form.hidden_field :corporacion_id, value: @corporacion_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_errors(@user.errors)%>
<%= form_for([:corporacion, @user], html: {role: "form",multipart: true, method: :put}) do |form| %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido %>
  </div>

  <div class="field">
    <%= form.label :rut %>
    <%= form.text_field :rut %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_field :correo %>
  </div>

  <div class="field">
    <%= form.label :contraseña %>
    <%= form.text_field :contraseña %>
  </div>

  <div class="field">
    <%= form.label :sucursal %>
    <%= form.text_field :sucursal %>
  </div>

  <div class="field">
    <%= form.label :filas %>
    <%= form.text_field :filas %>
  </div>

  <%= form.hidden_field :corporacion_id, value: @corporacion_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form_edit', user: @user %>


<%= link_to 'Show', corporacion_user_path(@corporacion_id,@user) %> |
<%= link_to 'Back', corporacion_users_path %>

app/views/users/index.html.erb
<%= stylesheet_link_tag "views/index_user.css" %>

<nav class="navbar navbar-expand-lg navbar-dark" style="background:#0E9CC8;">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="ml-auto">
      <div class="shape_perfil"></div>
      <div class="perfil">Tu perfil</div>
    </div>
  </div>
</nav>

<div class="rectangle">

  <div class="logo"></div>
  
  <div class="group">
    <div class="background">
      <div class="shape_usuarios"></div>
      <div class="corporaciones"> Usuarios</div>
    </div>
  </div>

  <%= link_to 'Cerrar Sesión', login_path, :class =>'cerrar_sesion'%>
  
  <div class="listado">Listado de Usuarios</div>

  <%= button_to 'Volver a Listado Corp.', corporacions_path,method: :get, :class => 'agregar2' %>

  <%= button_to 'Agregar Usuario', new_corporacion_user_path,method: :get, :class => 'agregar' %>

  <table class="table custom" >
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Rut</th>
      <th>Correo</th>
      <th>Contraseña</th>
      <th>Sucursal</th>
      <th>Filas</th>
      <th colspan="2">Config</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nombre %></td>
        <td><%= user.apellido %></td>
        <td><%= user.rut %></td>
        <td><%= user.correo %></td>
        <td><%= user.contraseña %></td>
        <td><%= user.sucursal %></td>
        <td><%= user.filas %></td>
        <td><%= link_to (fa_icon "edit"), edit_corporacion_user_path(@corporacion_id,user) %></td>
        <td><%= link_to (fa_icon "trash"), corporacion_user_path(@corporacion_id,user), method: :delete, data: { confirm: 'Are you sure?' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>    
  
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', corporacion_users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @user.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @user.apellido %>
</p>

<p>
  <strong>Rut:</strong>
  <%= @user.rut %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @user.correo %>
</p>

<p>
  <strong>Contraseña:</strong>
  <%= @user.contraseña %>
</p>

<p>
  <strong>Sucursal:</strong>
  <%= @user.sucursal %>
</p>

<p>
  <strong>Filas:</strong>
  <%= @user.filas %>
</p>

<%= link_to 'Edit', edit_corporacion_user_path(@corporacion_id,@user) %> |
<%= link_to 'Back', corporacion_users_path %>